#!/bin/bash

#Instructions: 
#
#chmod +x test.sh
#
#sudo ./test.sh

# UPDATE & UPGRADE SYSTEM. 

echo "UPDATING & UPGRADING THE SYSTEM:"
sudo apt-get update -yy -qq
sudo apt-get upgrade -yy -qq

# INSTALLING NET-TOOLS

echo "INSTALLING NET-TOOLS:"
sudo apt install net-tools -yy -qq

# INSTALLING NEOFETCH TO LOOK COOL
echo "INSTALLING NEOFETCH just to look cool:"
sudo apt install neofetch -y

# INSTALLING HTOP FOR MONITORING THE SYSTEM

echo "INSTALLING HTOP:"
sudo apt install htop

# INSTALLING NANO
echo "INSTALLING nano:"
sudo apt install nano -y

# INSTALLING LYNX FOR BROWSING

echo "INSTALLING LYNX:"
sudo apt install lynx -y

# INSTALLING MC (ctrl+o to switch between cli and folder layout. F3 to access files and Ecs to exit file.)

echo "INSTALLING MC:"
sudo apt install mc -y

echo "###################################################################################"
echo "Please be Patient: Installation will start now....... It may take some time :)"
echo "###################################################################################"


#PHP7 PPA
sudo apt-get install python-software-properties
sudo add-apt-repository ppa:ondrej/php


#Update the repositories

sudo apt-get update


#Apache, Php, MySQL and required packages installation

sudo apt-get -y install apache2 php7.0 libapache2-mod-php7.0 php7.0-mcrypt php7.0-curl php7.0-mysql php7.0-gd php7.0-cli php7.0-dev mysql-client
php7.0enmod mcrypt

#The following commands set the MySQL root password to root1234 when you install the mysql-server package.

sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password root1234'
sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password root1234'
sudo apt-get -y install mysql-server

#Restart all the installed services to verify that everything is installed properly

echo -e "\n"

service apache2 restart && service mysql restart > /dev/null

echo -e "\n"

php -v

if [ $? -ne 0 ]; then
   echo "Please Check the Install Services, There is some $(tput bold)$(tput setaf 1)Problem$(tput sgr0)"
else
   echo "Installed Services run $(tput bold)$(tput setaf 2)Sucessfully$(tput sgr0)"
fi

echo -e "\n"
